# Generated by Django 5.2.4 on 2025-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_sms_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("support", "Саппорт")],
                default="user",
                max_length=20,
                verbose_name="Тип аккаунта",
            ),
        ),
    ]
