# Generated by Django 5.2.4 on 2025-02-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("admins", "Администратор")],
                default="user",
                max_length=20,
                verbose_name="Тип аккаунта",
            ),
        ),
    ]
