# Generated by Django 5.2.4 on 2025-06-16 23:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="useradditionalinfo",
            options={
                "ordering": ["-created"],
                "verbose_name": "User Additional Information",
                "verbose_name_plural": "User Additional Information",
            },
        ),
        migrations.RemoveField(
            model_name="useradditionalinfo",
            name="sex",
        ),
        migrations.AddField(
            model_name="user",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="useradditionalinfo",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Муж", "Муж"), ("Жен", "Жен")],
                default="Муж",
                max_length=30,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Номер телефона в международном формате",
                max_length=16,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(12),
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: +79999999999",
                        regex="^\\+?1?\\d{11}$",
                    ),
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sms_notification",
            field=models.BooleanField(
                default=False,
                help_text="Включить/выключить SMS уведомления",
                verbose_name="SMS уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("user", "Обычный пользователь"), ("admins", "Администратор")],
                default="user",
                max_length=20,
                verbose_name="Тип аккаунта",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(
                help_text="Обязательное поле. Должно быть действительным email адресом.",
                max_length=255,
                unique=True,
                verbose_name="Логин",
            ),
        ),
        migrations.AlterField(
            model_name="useradditionalinfo",
            name="passport_number",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.RegexValidator(
                        "^[0-9]+$", "Номер паспорта должен содержать только цифры"
                    ),
                ],
                verbose_name="Номер паспорта",
            ),
        ),
        migrations.AlterField(
            model_name="useradditionalinfo",
            name="passport_photo_registered_address",
            field=models.ImageField(
                blank=True,
                help_text="Фото страницы паспорта с адресом регистрации",
                upload_to="passport_photos/%Y/%m/%d/",
                verbose_name="Фото страницы паспорта с адресом регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="useradditionalinfo",
            name="passport_photo_reversal",
            field=models.ImageField(
                blank=True,
                help_text="Фото главной страницы паспорта",
                upload_to="passport_photos/%Y/%m/%d/",
                verbose_name="Фото главной страницы паспорта",
            ),
        ),
        migrations.AlterField(
            model_name="useradditionalinfo",
            name="passport_series",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.RegexValidator(
                        "^[0-9]+$", "Серия паспорта должна содержать только цифры"
                    ),
                ],
                verbose_name="Серия паспорта",
            ),
        ),
        migrations.AlterField(
            model_name="useradditionalinfo",
            name="registered_address",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Адрес регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="useradditionalinfo",
            name="subdivision_code",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[django.core.validators.MinLengthValidator(7)],
                verbose_name="Код подразделения",
            ),
        ),
        migrations.AlterField(
            model_name="useradditionalinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
