# Generated by Django 5.2.4 on 2025-07-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_useradditionalinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradditionalinfo',
            options={'ordering': ['-created'], 'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
    ]
