# Generated by Django 3.2.4 on 2023-02-13 11:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=2, verbose_name='Символ валюты')),
                ('code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[0-9]+$')], verbose_name='Символ валюты')),
                ('short_name', models.CharField(max_length=2, verbose_name='Краткое название')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('number', models.UUIDField(default=uuid.uuid4, verbose_name='Номер счета')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('сurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.currency', verbose_name='Компания')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
