# Generated by Django 3.2.4 on 2023-02-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20230214_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Списание'), ('credit', 'Пополнение')], max_length=20, verbose_name='Тип платежа'),
        ),
    ]
