# Generated by Django 4.1.3 on 2023-02-17 12:33

from django.db import migrations


def adding_currencies(apps, schema_editor):

    Currency = apps.get_model('finance', 'Currency')
    currency_data = [
        Currency(symbol='₽', code=821, short_name='RUR', full_name='Российский рубль'),
        Currency(symbol='$', code=840, short_name='USD', full_name='доллар США'),
        Currency(symbol='€', code=978, short_name='EUR', full_name='евро'),
        Currency(symbol='¥', code=156, short_name='CNY', full_name='Китайский юань'),
    ]
    Currency.objects.bulk_create(currency_data)


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RunPython(adding_currencies),
    ]
