# Generated by Django 3.2.4 on 2023-03-02 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_currency_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('payment_id', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Id платежа')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('type', models.CharField(choices=[('refill', 'Ввод'), ('withdrawal', 'Вывод')], max_length=20, verbose_name='Тип платежа')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('waiting_for_capture', 'К зачислению'), ('cancelled', 'Отменено'), ('completed', 'Выполнено'), ('error', 'Ошибка')], max_length=20, verbose_name='Статус')),
                ('error', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Ошибка')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account', verbose_name='Счет')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.currency', verbose_name='Валюта')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('waiting_for_capture', 'К зачислению'), ('cancelled', 'Отменено'), ('completed', 'Выполнено'), ('error', 'Ошибка')], max_length=20, verbose_name='Статус')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.application', verbose_name='Заявка')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
