# Generated by Django 5.2.4 on 2025-06-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_application_applicationlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="type",
            new_name="payment_type",
        ),
    ]
