# Generated by Django 5.2.4 on 2025-07-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_type_application_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявка'},
        ),
    ]
